/* tslint:disable */
/* eslint-disable */
/**
 * Patrehub API
 * This is a description of what this does
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Benefit
 */
export interface Benefit {
    /**
     * 
     * @type {string}
     * @memberof Benefit
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Benefit
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Benefit
     */
    tierId: string;
    /**
     * 
     * @type {string}
     * @memberof Benefit
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Benefit
     */
    installationId: string;
    /**
     * 
     * @type {string}
     * @memberof Benefit
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof Benefit
     */
    repository: string;
    /**
     * 
     * @type {Date}
     * @memberof Benefit
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Benefit interface.
 */
export function instanceOfBenefit(value: object): value is Benefit {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('tierId' in value) || value['tierId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('installationId' in value) || value['installationId'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('repository' in value) || value['repository'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BenefitFromJSON(json: any): Benefit {
    return BenefitFromJSONTyped(json, false);
}

export function BenefitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Benefit {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'tierId': json['tier_id'],
        'type': json['type'],
        'installationId': json['installation_id'],
        'teamId': json['team_id'],
        'repository': json['repository'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function BenefitToJSON(json: any): Benefit {
    return BenefitToJSONTyped(json, false);
}

export function BenefitToJSONTyped(value?: Benefit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'tier_id': value['tierId'],
        'type': value['type'],
        'installation_id': value['installationId'],
        'team_id': value['teamId'],
        'repository': value['repository'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

