/* tslint:disable */
/* eslint-disable */
/**
 * Patrehub API
 * This is a description of what this does
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubInstallation } from './GithubInstallation';
import {
    GithubInstallationFromJSON,
    GithubInstallationFromJSONTyped,
    GithubInstallationToJSON,
    GithubInstallationToJSONTyped,
} from './GithubInstallation';

/**
 * 
 * @export
 * @interface GetGithubInstallationsResponse
 */
export interface GetGithubInstallationsResponse {
    /**
     * 
     * @type {number}
     * @memberof GetGithubInstallationsResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<GithubInstallation>}
     * @memberof GetGithubInstallationsResponse
     */
    installations?: Array<GithubInstallation>;
}

/**
 * Check if a given object implements the GetGithubInstallationsResponse interface.
 */
export function instanceOfGetGithubInstallationsResponse(value: object): value is GetGithubInstallationsResponse {
    return true;
}

export function GetGithubInstallationsResponseFromJSON(json: any): GetGithubInstallationsResponse {
    return GetGithubInstallationsResponseFromJSONTyped(json, false);
}

export function GetGithubInstallationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGithubInstallationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['total_count'] == null ? undefined : json['total_count'],
        'installations': json['installations'] == null ? undefined : ((json['installations'] as Array<any>).map(GithubInstallationFromJSON)),
    };
}

export function GetGithubInstallationsResponseToJSON(json: any): GetGithubInstallationsResponse {
    return GetGithubInstallationsResponseToJSONTyped(json, false);
}

export function GetGithubInstallationsResponseToJSONTyped(value?: GetGithubInstallationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['totalCount'],
        'installations': value['installations'] == null ? undefined : ((value['installations'] as Array<any>).map(GithubInstallationToJSON)),
    };
}

