/* tslint:disable */
/* eslint-disable */
/**
 * Patrehub API
 * This is a description of what this does
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatreonWebhook
 */
export interface PatreonWebhook {
    /**
     * 
     * @type {Date}
     * @memberof PatreonWebhook
     */
    lastAttemptedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatreonWebhook
     */
    numConsecutiveTimesFailed?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatreonWebhook
     */
    paused?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatreonWebhook
     */
    secret?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatreonWebhook
     */
    triggers?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatreonWebhook
     */
    uri?: string;
}

/**
 * Check if a given object implements the PatreonWebhook interface.
 */
export function instanceOfPatreonWebhook(value: object): value is PatreonWebhook {
    return true;
}

export function PatreonWebhookFromJSON(json: any): PatreonWebhook {
    return PatreonWebhookFromJSONTyped(json, false);
}

export function PatreonWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatreonWebhook {
    if (json == null) {
        return json;
    }
    return {
        
        'lastAttemptedAt': json['last_attempted_at'] == null ? undefined : (new Date(json['last_attempted_at'])),
        'numConsecutiveTimesFailed': json['num_consecutive_times_failed'] == null ? undefined : json['num_consecutive_times_failed'],
        'paused': json['paused'] == null ? undefined : json['paused'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'triggers': json['triggers'] == null ? undefined : json['triggers'],
        'uri': json['uri'] == null ? undefined : json['uri'],
    };
}

export function PatreonWebhookToJSON(json: any): PatreonWebhook {
    return PatreonWebhookToJSONTyped(json, false);
}

export function PatreonWebhookToJSONTyped(value?: PatreonWebhook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_attempted_at': value['lastAttemptedAt'] == null ? undefined : ((value['lastAttemptedAt']).toISOString()),
        'num_consecutive_times_failed': value['numConsecutiveTimesFailed'],
        'paused': value['paused'],
        'secret': value['secret'],
        'triggers': value['triggers'],
        'uri': value['uri'],
    };
}

