/* tslint:disable */
/* eslint-disable */
/**
 * Patrehub API
 * This is a description of what this does
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The request body for creating a new installation.
 * @export
 * @interface PostInstallationRequest
 */
export interface PostInstallationRequest {
    /**
     * The unique identifier for the installation.
     * @type {string}
     * @memberof PostInstallationRequest
     */
    id: string;
    /**
     * The name of the installation.
     * @type {string}
     * @memberof PostInstallationRequest
     */
    name: string;
}

/**
 * Check if a given object implements the PostInstallationRequest interface.
 */
export function instanceOfPostInstallationRequest(value: object): value is PostInstallationRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PostInstallationRequestFromJSON(json: any): PostInstallationRequest {
    return PostInstallationRequestFromJSONTyped(json, false);
}

export function PostInstallationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostInstallationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function PostInstallationRequestToJSON(json: any): PostInstallationRequest {
    return PostInstallationRequestToJSONTyped(json, false);
}

export function PostInstallationRequestToJSONTyped(value?: PostInstallationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

