/* tslint:disable */
/* eslint-disable */
/**
 * Patrehub API
 * This is a description of what this does
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Webhook
 */
export interface Webhook {
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    webhookId?: string;
    /**
     * 
     * @type {string}
     * @memberof Webhook
     */
    webhookSecret?: string;
    /**
     * 
     * @type {Date}
     * @memberof Webhook
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the Webhook interface.
 */
export function instanceOfWebhook(value: object): value is Webhook {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function WebhookFromJSON(json: any): Webhook {
    return WebhookFromJSONTyped(json, false);
}

export function WebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webhook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'webhookId': json['webhook_id'] == null ? undefined : json['webhook_id'],
        'webhookSecret': json['webhook_secret'] == null ? undefined : json['webhook_secret'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function WebhookToJSON(json: any): Webhook {
    return WebhookToJSONTyped(json, false);
}

export function WebhookToJSONTyped(value?: Webhook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'webhook_id': value['webhookId'],
        'webhook_secret': value['webhookSecret'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

