name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest # Specifies the operating system for the job.

    steps:
      - name: Checkout Repo # Checks out the repository.
        uses: actions/checkout@v4

      - name: Create Node Environment # Sets up Node.js environment.
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: Install Packages and Build Application # Installs npm packages and builds the Vue.js application.
        run: |
          npm ci
          npm run build
